# Generated by Django 4.2.3 on 2023-08-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_accessrecord_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='empno',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
